apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-api-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "myapp.selectorLabels" (dict "component" "api" "root" .) | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-ui-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    {{- include "myapp.selectorLabels" (dict "component" "ui" "root" .) | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.service.targetPort }}
