#!/bin/bash
LOG="/tmp/devops-exam/logs/app.log"

echo "=== LOG ANALYSIS REPORT ==="
echo "File: $LOG"
echo ""
echo "Total lines:"
wc -l < "$LOG"
echo ""
echo "ERROR count:"
grep -c "ERROR" "$LOG"
echo ""
echo "WARNING count:"
grep -c "WARNING" "$LOG"
echo ""
echo "All ERROR lines:"
grep "ERROR" "$LOG"
echo ""
echo "Last 5 entries:"
tail -5 "$LOG"
echo ""
echo "=== END ==="
